# a = input("Enter number 1:")
# b = input("Enter number 2:")
# print("Enter number 1 : ",a)
# print("Enter number 2 : ", b)
# print("Sum of  number  : ", a+b)
a = int(input("Enter number 1:"))
b = int(input("Enter number 2:"))
print("Enter number 1 : ",a)
print("Enter number 2 : ", b)
print("Sum of  number  : ", a+b)
