dic = {}
n = input("Enter your name: ")
m = input("Enter your langauge : ")
dic.update({n  : m})
n = input("Enter your name: ")
m = input("Enter your langauge : ")
dic.update({n  : m})
n = input("Enter your name: ")
m = input("Enter your langauge : ")
dic.update({n  : m})
n = input("Enter your name: ")
m = input("Enter your langauge : ")
dic.update({n  : m})
print(dic)