version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"  # Exposing Zookeeper's default port for any client access

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"  # Exposing Kafka's default port to your host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Advertise Kafka to be reachable on localhost
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Allows external connections
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT  # Specifies the listener protocol
      KAFKA_LISTENER_NAME_PLANE: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
